### ISSUE TITLE
Roadmap & Suggestions

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/pidi-spotify#1]
This isn't a super complex package, and I intend to keep the feature-set pretty narrow although it could be expanded to display this same information on almost any other LCD display with some tweaks.

However for now my roadmap is as follows:

* [x] Add support for reading options from a config file `/etc/default/pidi_spotify` perhaps?
* [x] Add support for this program to be run as a *client* allowing it to interpret Raspotify hook environment variables directly and effectively control its server counterpart via the FIFO.
* [ ] Add support for this program to be run as a daemon... probably doesn't need forking and all that fancy stuff, but might be nice?
* [x] Allow cache path to be configured in settings/args
* [x] Add logging with configurable output
* [x] Maybe add some indication of whether the track is currently playing or paused (should be possible)
* [x] Tidy up this library and turn into a Python package with an endpoint serving the `pidi_spotify` "binary".
* [ ] Test support for this LCD suggested by @dglaude https://shop.pimoroni.com/products/adafruit-mini-pitft-1-3-240x240-tft-add-on-for-raspberry-pi (should work- same resolution and driver - Data/Command = 25, Backlight = 22)

If you have any suggestions, desires or requests then please add them here. *However* I intend to keep this tool pretty slimline and wont be adding any complicated features. 

Here's what it will *never* do:

* It will never support any kind of button input, if you want to use the buttons for something use `RPi.GPIO` or `gpiozero` and write your own script
* This also means no volume control, no skip and no play/pause on Pirate Audio. Sorry. It's not possible.
* In fact - It will never be able to control Spotify or read private information from your Spotify account. It will only ever know the TRACK_ID you have played via Spotify Connect, the VOLUME set, and the POSITION_MS into that track you have seek'd.

Note: This *will not* run alongside Mopidy and is not indended for Mopidy users. If you're installing Raspotify alongside Mopidy then you can use `mpc` to push Spotify tracks into Mopidy. See my last post here: https://github.com/pimoroni/pirate-audio/issues/17

**Comment by Gadgetoid** [comment]
It should be possible to use the Adafruit Mini PiTFT 1.3" by editing `/etc/default/pidi-spotify` and adding:

```
spi-data-command-pin=25
spi-backlight-pin=22
```

If anyone wants to give it a go, this requires the `devel` version of the code in the pending PR: https://github.com/pimoroni/pidi-spotify/pull/2

**Comment by robrecord** [comment]
Will it be possible to clear the display and turn the backlight off when Spotify has stopped?

**Comment by Gadgetoid** [comment]
Possibly, I think there's a "stop" command issued, but I don't know what circumstances this is triggered by.

**Comment by JasonLG1979** [comment]
@Gadgetoid Not so much a suggestion but you and/or your users may find the ```asound.conf``` in [this Gist](https://gist.github.com/JasonLG1979/f29cb0f14218a3b20db5d32c2cfae5ed) useful.

asound.conf can be a bit of black magic for most people, the above Gist vastly simplifies audio configuration and tweaking. It creates sorta a ```plughw``` on steroids. It allows you to change pretty much everything except channel count and mapping by editing only 1 line (well, 3 if your DAC isn't CARD 0).

See: https://github.com/dtcooper/raspotify/issues/298#issuecomment-702599600

**Comment by EvanHopps** [comment]
Would there be a way to rotate the display like there was in Mopidy? I my Pi on the wall in its case with the LCD on the bottom because of space requirements and the direction my aux jack needed to point. In Mopidy I used Rotate=270 in the config file. Now I don't use Mopidy at all and didn't see a good place to rotate the display.
